Release/1.0.0 - solution-pack-fortimanager-ztp-framework
fortinet-fortisoar/solution-pack-fortimanager-ztp-framework pull request #2
Opened 2023-07-27 20:27 UTC by fortijames

Please review and merge for release. 

This does require the pending pull request of the new FortiManager Connector ( https://github.com/fortinet-fortisoar/connector-fortinet-fortimanager-json-rpc/pull/1 ).

2023-08-04 07:41 UTC, cs-rohit-khune requested changes

2023-08-04 07:41 UTC, cs-rohit-khune commented on connectors/data.json
> +        "version": "1.0.0",
Please remove the version key from the data dictionary since specifying it will always install the mentioned version instead of the latest connector version.

2023-08-04 07:41 UTC, cs-rohit-khune commented on info.json
> +    "dependencies": [],
Please include the "SOAR Framework" as a dependency package since you are importing an announcements record, and the announcement module is part of the "SOAR Framework" solution pack.

2023-08-04 07:41 UTC, cs-rohit-khune commented on info.json
> +    "publisher": "Fortinet",
Please mention publisher as "Fortinet CSE"

2023-08-04 07:41 UTC, cs-rohit-khune commented on playbooks/FortiManager(FMG)-Buttons/Add Device to Device Group from Device Record.json
Please rename playbook collection names:

For collection names, follow this nomenclature:

1. Framework Specific SPs: "10 - SP - <SP Name> - <Collection Name>" (e.g., "10 - SP - FortiManager ZTP Flow - FortiManager(FMG)-Buttons")

2. UseCase Specific SPs: "02 - Use Cases - <SP Name> - <Collection Name>"

2023-08-04 07:41 UTC, cs-rohit-khune commented on modules/devices/mmd.json
> +    "peerReplicable": false,
Some key settings are missing in all modules, as shown in the screenshot. Please confirm if the current settings work for you or configure the relevant settings.

![image](https://github.com/fortinet-fortisoar/solution-pack-fortimanager-ztp-framework/assets/46894140/035ebf4d-35e6-460e-a506-df8fe6b723cf)

2023-08-09 06:24 UTC, cs-rohit-khune approved these changes

2023-08-09 07:51 UTC, cs-suyog-jinturkar approved these changes
Reviewed and approved by Rohit

2023-08-09 07:51 UTC, merged